jobs:

  uberjar:
    name: Build uberjar
    run_when:
      on any branch:
        type: branch
        include_match: ^.*$
    context:
      tasks:
        build:
          traits:
            asdf: true
          scripts:
            uberjar:
              body: |
                #!/usr/bin/env bash
                set -euo pipefail
                git submodule update --init --recursive --force
                ./bin/build

  deploy_environment:
    name: Check working deploy environment
    run_when:
      on any branch:
        type: branch
        include_match: ^.*$
    context:
      tasks:
        check_deploy_environment:
          traits:
            asdf: true
          scripts:
            check_ansible_version:
              body: |
                #!/usr/bin/env bash
                set -euo pipefail
                ./bin/ansible --version | grep -E '^ansible \[core 2\..+]' || (echo "Ansible version 2.x is required" >&2 ; exit 1)
